name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Tidy
        run: go mod tidy
      - name: Build
        run: go build ./...
      - name: Test (with coverage)
        run: go test ./... -coverprofile=coverage.out
      - name: Security scan (govulncheck)
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: '1.23'
          go-package: ./...
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61


