name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate semver tag and VERSION file
        run: |
          echo "Tag: ${GITHUB_REF_NAME}"
          if ! [[ "${GITHUB_REF_NAME}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z\.-]+)?$ ]]; then
            echo "Invalid semver tag: ${GITHUB_REF_NAME}"; exit 1; fi
          if [ "$(cat VERSION)" != "${GITHUB_REF_NAME}" ]; then
            echo "VERSION mismatch: $(cat VERSION) vs ${GITHUB_REF_NAME}"; exit 1; fi
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Build binaries
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=${GITHUB_REF_NAME}" -o dist/gauditor-linux-amd64 ./cmd/gauditor
          GOOS=darwin GOARCH=arm64 go build -ldflags "-X main.version=${GITHUB_REF_NAME}" -o dist/gauditor-darwin-arm64 ./cmd/gauditor
          GOOS=windows GOARCH=amd64 go build -ldflags "-X main.version=${GITHUB_REF_NAME}" -o dist/gauditor-windows-amd64.exe ./cmd/gauditor
      - name: Checksums
        run: |
          (cd dist && shasum -a 256 * > SHA256SUMS)
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            dist/*

